(module
  ;; Generated by BMB compiler (v0.12.1)

  ;; Memory: 1 pages (64KB)
  (memory (export "memory") 1)

  ;; Globals for runtime
  (global $heap_ptr (mut i32) (i32.const 1024))
  (global $io_buf i32 (i32.const 0))

  ;; Runtime imports
  (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $proc_exit (param i32)))

  ;; Function types
  (type $t_println_i64 (func (param i64)))
  (type $t_print_i64 (func (param i64)))
  (type $t_exit (func (param i32)))
  (type $t_assert (func (param i32)))
  (type $type_0 (func (result i64)))
  (type $type_1 (func (result i64)))
  (type $type_2 (func (result i64)))

  ;; Runtime helper functions
  ;; $i64_to_str: Convert i64 to decimal string at $io_buf
  ;; Returns: length of string
  (func $i64_to_str (param $val i64) (result i32)
    (local $len i32)
    (local $digit i64)
    (local $ptr i32)
    (local $neg i32)
    (local $start i32)

    ;; Handle negative numbers
    (if (i64.lt_s (local.get $val) (i64.const 0))
      (then
        (local.set $neg (i32.const 1))
        (local.set $val (i64.sub (i64.const 0) (local.get $val)))
      )
    )

    ;; Start at end of buffer (offset 100) and work backwards
    (local.set $ptr (i32.const 100))

    ;; Handle zero specially
    (if (i64.eq (local.get $val) (i64.const 0))
      (then
        (i32.store8 (global.get $io_buf) (i32.const 48))  ;; '0'
        (return (i32.const 1))
      )
    )

    ;; Extract digits (reversed)
    (block $done
      (loop $extract
        (br_if $done (i64.eq (local.get $val) (i64.const 0)))
        (local.set $digit (i64.rem_u (local.get $val) (i64.const 10)))
        (local.set $val (i64.div_u (local.get $val) (i64.const 10)))
        (local.set $ptr (i32.sub (local.get $ptr) (i32.const 1)))
        (i32.store8 (local.get $ptr) (i32.add (i32.const 48) (i32.wrap_i64 (local.get $digit))))
        (local.set $len (i32.add (local.get $len) (i32.const 1)))
        (br $extract)
      )
    )

    ;; Add minus sign if negative
    (if (local.get $neg)
      (then
        (local.set $ptr (i32.sub (local.get $ptr) (i32.const 1)))
        (i32.store8 (local.get $ptr) (i32.const 45))  ;; '-'
        (local.set $len (i32.add (local.get $len) (i32.const 1)))
      )
    )

    ;; Copy to beginning of buffer
    (local.set $start (i32.const 0))
    (block $copy_done
      (loop $copy
        (br_if $copy_done (i32.eq (local.get $start) (local.get $len)))
        (i32.store8 (i32.add (global.get $io_buf) (local.get $start))
          (i32.load8_u (local.get $ptr)))
        (local.set $start (i32.add (local.get $start) (i32.const 1)))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
        (br $copy)
      )
    )

    (local.get $len)
  )

  ;; $println: Print i64 value with newline to stdout
  (func $println (param $val i64)
    (local $len i32)
    (local $written i32)

    ;; Convert number to string
    (local.set $len (call $i64_to_str (local.get $val)))

    ;; Add newline
    (i32.store8 (i32.add (global.get $io_buf) (local.get $len)) (i32.const 10))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))

    ;; Set up iovec at offset 200: [pointer, length]
    (i32.store (i32.const 200) (global.get $io_buf))  ;; iov_base
    (i32.store (i32.const 204) (local.get $len))       ;; iov_len

    ;; fd_write(fd=1, iovs=200, iovs_len=1, nwritten=208)
    (drop (call $fd_write
      (i32.const 1)    ;; fd: stdout
      (i32.const 200)  ;; iovs
      (i32.const 1)    ;; iovs_len
      (i32.const 208)  ;; nwritten
    ))
  )

  ;; $print: Print i64 value without newline to stdout
  (func $print (param $val i64)
    (local $len i32)

    ;; Convert number to string
    (local.set $len (call $i64_to_str (local.get $val)))

    ;; Set up iovec at offset 200
    (i32.store (i32.const 200) (global.get $io_buf))
    (i32.store (i32.const 204) (local.get $len))

    ;; fd_write(fd=1, iovs=200, iovs_len=1, nwritten=208)
    (drop (call $fd_write
      (i32.const 1)
      (i32.const 200)
      (i32.const 1)
      (i32.const 208)
    ))
  )

  ;; $exit: Terminate process with exit code
  (func $exit (param $code i32)
    (call $proc_exit (local.get $code))
  )

  ;; $assert: Exit with code 1 if condition is false
  (func $assert (param $cond i32)
    (if (i32.eqz (local.get $cond))
      (then (call $proc_exit (i32.const 1)))
    )
  )

  (func $always  (result i64)
    i64.const 42
    return
  )

  (func $wasm_only  (result i64)
    i64.const 100
    return
  )

  (func $main  (result i64)
    (local $_t0 i64)
    call $always
    local.set $_t0
    local.get $_t0
    return
  )

  ;; Exports
  (export "always" (func $always))
  (export "wasm_only" (func $wasm_only))
  (export "_start" (func $main))
  (export "main" (func $main))

)
